import { useState } from "react";
import { motion, AnimatePresence } from "motion/react";

import { predictMalaria } from "./api";
import type { PatientData } from "./types";
import Footer from "./components/footer";
import StepDots from "./components/StepDots";
import Page1 from "./components/pages/page-1";
import Page2 from "./components/pages/page-2";
import Page3 from "./components/pages/page-3";

// ─── Types ────────────────────────────────────────────────────────────────────

type Step = "demographics" | "symptoms" | "result";


// ─── Constants ────────────────────────────────────────────────────────────────

const ORANGE = "#f97316";
const ORANGE_DARK = "#ea580c";

const INITIAL_FORM: PatientData = {
  age: "",
  sex: 1,
  fever: 0,
  headache: 0,
  abdominal_pain: 0,
  malaise: 0,
  dizziness: 0,
  vomiting: 0,
  confusion: 0,
  backache: 0,
  chest_pain: 0,
  coughing: 0,
  joint_pain: 0,
};

const SYMPTOMS: { key: keyof PatientData; label: string; desc: string }[] = [
  {
    key: "fever",
    label: "Fever",
    desc: "Elevated body temperature above 38°C (100.4°F), often with chills and sweating.",
  },
  {
    key: "headache",
    label: "Headache",
    desc: "Persistent or throbbing pain in the head, temples, or behind the eyes.",
  },
  {
    key: "abdominal_pain",
    label: "Abdominal Pain",
    desc: "Cramping or aching discomfort in the stomach or lower abdomen.",
  },
  {
    key: "malaise",
    label: "Body Malaise",
    desc: "General feeling of discomfort, fatigue, or lack of wellbeing.",
  },
  {
    key: "dizziness",
    label: "Dizziness",
    desc: "Sensation of spinning, lightheadedness, or unsteadiness.",
  },
  {
    key: "vomiting",
    label: "Vomiting",
    desc: "Forceful expulsion of stomach contents; may accompany nausea.",
  },
  {
    key: "confusion",
    label: "Confusion",
    desc: "Disorientation or altered mental state. Can indicate severe malaria.",
  },
  {
    key: "backache",
    label: "Backache",
    desc: "Pain or stiffness in the lower or upper back region.",
  },
  {
    key: "chest_pain",
    label: "Chest Pain",
    desc: "Tightness, pressure, or sharp pain in the chest area.",
  },
  {
    key: "coughing",
    label: "Coughing",
    desc: "Repeated, forceful expulsion of air from the lungs.",
  },
  {
    key: "joint_pain",
    label: "Joint Pain",
    desc: "Aching or stiffness in joints such as knees, elbows, or wrists.",
  },
];

const PAGE_VARIANTS = {
  enter: { opacity: 0, x: 40 },
  center: { opacity: 1, x: 0 },
  exit: { opacity: 0, x: -40 },
};

const SHAKE_DURATION_MS = 600;

// ─── Helpers ──────────────────────────────────────────────────────────────────

function getMapUrl(location: string): string {
  if (!location) return "";
  return `https://www.google.com/maps?q=hospitals+near+${encodeURIComponent(location)}&output=embed`;
}

function getMapHref(location: string): string {
  if (!location) return "#";
  return `https://www.google.com/maps/search/hospitals+near+${encodeURIComponent(location)}`;
}

function countSymptoms(form: PatientData): number {
  return SYMPTOMS.reduce((n, s) => n + (form[s.key] as number), 0);
}

/** Builds a mailto: link pre-filled with the patient's diagnosis report. */
function buildContactMailHref(
  form: PatientData,
  positive: boolean,
  confPct: number,
): string {
  const selectedSymptoms = SYMPTOMS.filter((s) => form[s.key] === 1)
    .map((s) => `  • ${s.label}`)
    .join("\n");

  const ageGroup = Number(form.age) <= 18 ? "Pediatric" : "Adult";
  const sex = form.sex === 0 ? "Female" : "Male";
  const diagnosis = positive ? "POSITIVE — Malaria Detected" : "NEGATIVE — No Malaria Detected";

  const body = [
    "Dear NMEP,",
    "",
    "Please find below a MalariaDx AI diagnosis report for your review.",
    "",
    "── Patient Information ──────────────────",
    `Age Group : ${ageGroup}`,
    `Sex       : ${sex}`,
    "",
    "── Presenting Symptoms ─────────────────",
    selectedSymptoms || "  None selected",
    "",
    "── Diagnosis Result ────────────────────",
    `Result    : ${diagnosis}`,
    `Confidence: ${confPct.toFixed(1)}%`,
    "",
    "This report was generated by MalariaDx (AI-assisted, XGBoost · AUC 0.9984).",
    "It is intended for clinical decision support only and does not replace",
    "professional medical advice or laboratory confirmation.",
    "",
    "Regards,",
    "MalariaDx System",
  ].join("\n");

  const subject = `MalariaDx Report — ${positive ? "Positive" : "Negative"} (Confidence: ${confPct.toFixed(1)}%)`;

  return `mailto:info@nmep.gov.ng?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;
}

// ─── Style Constants ──────────────────────────────────────────────────────────

const styles = {
  root: {
    minHeight: "100vh",
    background: "linear-gradient(145deg, #fffbf7 0%, #fff7ed 45%, #ffedd5 100%)",
    fontFamily: "'DM Sans', sans-serif",
    position: "relative",
    overflowX: "hidden",
  } as React.CSSProperties,

  blobTopRight: {
    position: "fixed",
    top: -130,
    right: -130,
    width: 420,
    height: 420,
    borderRadius: "50%",
    background: "radial-gradient(circle, rgba(251,146,60,0.16) 0%, transparent 70%)",
    pointerEvents: "none",
  } as React.CSSProperties,

  blobBottomLeft: {
    position: "fixed",
    bottom: -90,
    left: -90,
    width: 360,
    height: 360,
    borderRadius: "50%",
    background: "radial-gradient(circle, rgba(253,186,116,0.18) 0%, transparent 70%)",
    pointerEvents: "none",
  } as React.CSSProperties,

  pageWrapper: {
    maxWidth: 640,
    margin: "0 auto",
    padding: "clamp(1.5rem, 5vw, 3rem) clamp(1rem, 4vw, 1.5rem)",
    position: "relative",
    zIndex: 10,
  } as React.CSSProperties,

  wordmark: {
    display: "flex",
    alignItems: "center",
    gap: "0.6rem",
    marginBottom: "1.75rem",
  } as React.CSSProperties,

  logoIcon: {
    width: 36,
    height: 36,
    borderRadius: 10,
    background: `linear-gradient(135deg, ${ORANGE}, ${ORANGE_DARK})`,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "1.1rem",
    boxShadow: "0 4px 14px rgba(249,115,22,0.35)",
  } as React.CSSProperties,

  logoText: {
    fontFamily: "'Fraunces', serif",
    fontWeight: 900,
    fontSize: "1.15rem",
    color: "#1c1917",
  } as React.CSSProperties,

  logoBadge: {
    marginLeft: "auto",
    fontSize: "0.67rem",
    fontWeight: 600,
    letterSpacing: "0.06em",
    color: ORANGE_DARK,
    background: `rgba(249,115,22,0.1)`,
    border: `1px solid rgba(249,115,22,0.22)`,
    padding: "0.2rem 0.7rem",
    borderRadius: 999,
  } as React.CSSProperties,

  headlineWrapper: {
    marginBottom: "1.75rem",
  } as React.CSSProperties,

  headline: {
    fontFamily: "'Fraunces', serif",
    fontWeight: 900,
    fontSize: "clamp(1.75rem, 6vw, 2.4rem)",
    color: "#1c1917",
    lineHeight: 1.1,
    letterSpacing: "-0.03em",
    marginBottom: "0.4rem",
  } as React.CSSProperties,

  headlineAccent: {
    color: ORANGE,
    fontStyle: "italic",
  } as React.CSSProperties,

  subheadline: {
    fontSize: "0.87rem",
    color: "#78716c",
    fontWeight: 300,
    lineHeight: 1.65,
  } as React.CSSProperties,
} as const;

// ─── Main Component ───────────────────────────────────────────────────────────

export default function App() {
  const [form, setForm] = useState<PatientData>(INITIAL_FORM);
  const [location, setLocation] = useState("");
  const [result, setResult] = useState<any>(null);
  const [loading, setLoading] = useState(false);
  const [step, setStep] = useState<Step>("demographics");
  const [shakeSymptoms, setShakeSymptoms] = useState(false);

  const symptomCount = countSymptoms(form);

  // ── Handlers ────────────────────────────────────────────────────────────────

  function handleChange(key: keyof PatientData, value: number) {
    setForm((prev) => ({ ...prev, [key]: value }));
  }

  function goToSymptoms() {
    setStep("symptoms");
  }

  function handleReset() {
    setStep("demographics");
    setResult(null);
  }

  async function handleSubmit() {
    if (symptomCount === 0) {
      setShakeSymptoms(true);
      setTimeout(() => setShakeSymptoms(false), SHAKE_DURATION_MS);
      return;
    }

    setLoading(true);
    setResult(null);

    try {
      const res = await predictMalaria(form);
      setResult(res);
      setStep("result");
    } catch {
      alert("Backend error — make sure the FastAPI server is running.");
    } finally {
      setLoading(false);
    }
  }

  // ── Derived values ───────────────────────────────────────────────────────────

  const positive = result?.prediction === 1;
  const posProb = (result?.probabilities?.positive ?? 0) * 100;
  const negProb = (result?.probabilities?.negative ?? 0) * 100;
  const confPct = (result?.confidence ?? 0) * 100;
  const mapUrl = getMapUrl(location);
  const mapHref = getMapHref(location);
  const contactMailHref = buildContactMailHref(form, positive, confPct);

  // ── Render ───────────────────────────────────────────────────────────────────

  return (
    <div style={styles.root}>
      {/* ── Decorative blobs ── */}
      <div aria-hidden style={styles.blobTopRight} />
      <div aria-hidden style={styles.blobBottomLeft} />

      <div style={styles.pageWrapper}>
        {/* ── Wordmark ── */}
        <motion.div
          initial={{ opacity: 0, y: -14 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.45 }}
          style={styles.wordmark}
        >
          <div style={styles.logoIcon}>🦟</div>
          <span style={styles.logoText}>MalariaDx</span>
          <span style={styles.logoBadge}>XGBoost · AUC 0.9984</span>
        </motion.div>

        {/* ── Headline ── */}
        <motion.div
          initial={{ opacity: 0, y: 18 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.45, delay: 0.1 }}
          style={styles.headlineWrapper}
        >
          <h1 style={styles.headline}>
            Symptom-Based
            <br />
            <span style={styles.headlineAccent}>Diagnosis</span>
          </h1>
          <p style={styles.subheadline}>
            AI-assisted malaria prediction · For clinical decision support only.
          </p>
        </motion.div>

        {/* ── Step indicator ── */}
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: 0.2 }}
        >
          <StepDots current={step} />
        </motion.div>

        {/* ── Pages ── */}
        <AnimatePresence mode="wait">
          {step === "demographics" && (
            <Page1
              key="demographics"
              form={form}
              handleChange={handleChange}
              location={location}
              setLocation={setLocation}
              goToSymptoms={goToSymptoms}
              pageVariants={PAGE_VARIANTS}
            />
          )}

          {step === "symptoms" && (
            <Page2
              key="symptoms"
              form={form}
              handleChange={handleChange}
              symptomCount={symptomCount}
              loading={loading}
              shakeSymptoms={shakeSymptoms}
              handleSubmit={handleSubmit}
              goBack={() => setStep("demographics")}
              pageVariants={PAGE_VARIANTS}
              symptoms={SYMPTOMS}
            />
          )}

          {step === "result" && result && (
            <Page3
              key="result"
              result={result}
              positive={positive}
              symptomCount={symptomCount}
              form={form}
              confPct={confPct}
              negProb={negProb}
              posProb={posProb}
              location={location}
              mapUrl={mapUrl}
              mapHref={mapHref}
              contactMailHref={contactMailHref}
              handleReset={handleReset}
              pageVariants={PAGE_VARIANTS}
            />
          )}
        </AnimatePresence>

        {/* ── Footer ── */}
        <Footer />
      </div>
    </div>
  );
}